mechDogSite/mechDogSite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include


from . import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',  include('userManage.urls')),
    url(r'^$' , views.main),
    url(r'^visitor/',  include('visitorManage.urls')),
]

mechDogSite/userManage/urls.py
from django.conf.urls import url

from . import views,command

app_name='userManage'

urlpatterns = [
    url(r'^$',views.main,name='user'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^command$',command.operate,name='operate'),
]

mechDogSite/visitorManage/urls.py
from django.conf.urls import url

from . import views
app_name='visitorManage'
urlpatterns = [
    url(r'^$',views.main,name='visitor'),
]

mechDogSite/userManage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50,blank=True)
    password = models.CharField(max_length=50,blank=True)
    uid=models.IntegerField(primary_key=True)
    def __unicode__(self):
        return self.username

mechDogSite/visitorManage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mechDogSite/mechDogSite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,render_to_response
from django.http import cookie
from django.http import HttpRequest,HttpResponse,HttpResponseRedirect

def main(request):
    return render(request,"home.html")

mechDogSite/userManage/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,render_to_response
from django.http import cookie
from django.http import HttpRequest,HttpResponse,HttpResponseRedirect
from django import forms

from models import User
# Create your views here.

class UserForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label='password', widget=forms.PasswordInput())

def TokenCheck(request):
    username = request.COOKIES.get('username', '')
    user = User.objects.filter(username__exact=username)
    if user:
        return user[0]
    else:
        return None
def TokenGenerate(response,user):
    response.set_cookie('username', user.username, 3600)
    return response
def TokenRemove(response):
    response.delete_cookie('username')
    return response

def main(request):
    user=TokenCheck(request)
    if(user):
        # 登录
        return render(request, 'userManage/main_Y.html', {'user':user})
    else:
        # 未登录
        return render(request, 'userManage/main_N.html', {})

def register(request):
    return render(request, 'userManage/main_N.html', {'warning': ['registration not allowed now!','please contact adminstartors.']})
    '''if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            # 获得表单数据
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            if(len(User.objects.filter(username__exact = username))!=0):
                return render(request, 'userManage/main_N.html', {'warning':'please change a username!'})
            # 添加到数据库
            User.objects.create(username=username, password=password)
            return HttpResponse('regist success!!')
    return HttpResponseRedirect('/user/')'''

def login(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            #获取表单用户密码
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            #获取的表单数据与数据库进行比较
            user = User.objects.filter(username__exact = username,password__exact = password)
            if user:
                #比较成功，跳转
                response = HttpResponseRedirect('/user/')
                # 将username写入浏览器cookie,失效时间为3600
                response=TokenGenerate(response,user[0])
                return response
            else:
                return render(request, 'userManage/main_N.html', {'warining':['incorrect!']})
    return HttpResponseRedirect('/user/')

def logout(request):
    response = HttpResponseRedirect('/user/')
    # 清理cookie里保存username
    return TokenRemove(response)

mechDogSite/visitorManage/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def main(request):
    return HttpResponse("Visitor")

mechDogSite/userManage/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>User {{user.username}}</title>
<link type="text/css" rel="stylesheet" href="/static/stl/home_styles.css" media="all" />
  </head>
  <body id="body">
        <img src="/static/img/header.png" id="body_Image" >
        <img src="/static/img/divider.png" class="body_divider">
        <div id="nav">
          <a class="navButton" href="#">
            <img class="navButtonImg" src="/static/img/viewPic.png">
            <img class="navButtonText" src="/static/img/view.png">
          </a>
          <a class="navButton" href="#">
            <img class="navButtonImg" src="/static/img/surroundingPic.png">
            <img class="navButtonText" src="/static/img/surrounding.png">
          </a>
          <a class="navButton" href="#">
            <img class="navButtonImg" src="/static/img/imagePic.png">
            <img class="navButtonText" src="/static/img/image.png">
          </a>
          <a class="navButton" href="#">
            <img class="navButtonImg" src="/static/img/interactPic.png">
            <img class="navButtonText" src="/static/img/interact.png">
          </a>
        </div>
        <div id="body_divider"><br></div>
        <div id="AboutUs">
          <img src="/static/img/AboutUsText.png" style="width:50%;padding-left:25%;">
          <div id="AboutUsNav">
            <li id="aboutUsMember" class="AboutUsBtn" href="#">
              <img class="AboutUsBtnImg" src="/static/img/memberPic.png" >
              <img class="AboutUsBtnImg" src="/static/img/member.png">
            </li>
            <li id="AboutUsCooperation" class="AboutUsBtn" href="#">
              <img class="AboutUsBtnImg" src="/static/img/cooperationPic.png" >
              <img class="AboutUsBtnImg" src="/static/img/cooperation.png">
            </li>
            <li id="aboutUsProgress" class="AboutUsBtn" href="#">
              <img class="AboutUsBtnImg" src="/static/img/progressPic.png" >
              <img class="AboutUsBtnImg" src="/static/img/progress.png">
            </li>
          </div>
        </div>
        <div class="body_divider"><br></div>
        <div id="bottom">
        <label style="float:center;padding-left:40%;padding:right:40%">copyright©mechdogTeam17</label>
      </div>
  </body>
</html>

mechDogSite/userManage/templates/userManage/main_N.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>user</title>
</head>
<body>
{%if warning%}
<p>
    {%for eachline in warning%}
    {{eachline}}<br>
    {%endfor%}
</p>
{%endif%}
<form method="POST" >
    <p>{% csrf_token %}</p>
    <p>User Name <input type="text" name="username" ></p>
    <p>Password <input type="password" name="password"></p>
    <input type="submit" value="登录" formaction="{% url 'userManage:login'%}">
    <input type="submit" value="注册" formaction="{% url 'userManage:register'%}"><br>
</form>
</body>
</html>

mechDogSite/userManage/templates/userManage/main_Y.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>User {{user.username}}</title>
    <link rel="stylesheet" type="text/css" media="all" href="../../static/userManage/nav_styles.css">
    <link rel="stylesheet" type="text/css" media="all" href="/static/userManage/nav_styles.css">
    <link rel="stylesheet" type="text/css" media="all" href="../../static/userManage/oper_styles.css">
    <link rel="stylesheet" type="text/css" media="all" href="/static/userManage/oper_styles.css">
    </head>
  {%load static%}
  <script type="text/javascript" language="javascript">
  function iFrameHeight(o) {
      var ifm = document.getElementById("displayer");
      var subWeb = document.frames ?
        document.frames["displayer"].document :
        ifm.contentDocument;
      if (ifm != null && subWeb != null) {
          ifm.height = subWeb.body.scrollHeight;
          ifm.width =subWeb.body.scrollWidth;
      }
 }
  }
  </script>
  <body>
    <div id="nav">
      <li class="dropDownBtn">
        <a class="dropDownLabel">User</a>
        <div class="dropDownContent">
          <a class="dropDownContentItem" href="#">{{user.username}}</a>
          <a class="dropDownContentItem" href="{% url 'userManage:logout' %}">logout</a>
        </div>
      </li>
      <li class="dropDownBtn">
        <a class="dropDownLabel">Operate</a>
        <div class="dropDownContent">
          <a class="dropDownContentItem">Video</a>
        </div>
      </li>
    </div>
    {%if displayer%}
    <div id="viewcontainer">
      <div id="view">
        <iframe name="displayer" seamless="yes"
              scrolling="yes"   marginwidth="0px"
              marginheight="0px" width=90%
              height=600px  frameborder="0"
              align="middle"
              src="{{displayer.displayurl}}"
              style="zoom:100%">
        &lt;p&gt;您的浏览器不支持 iframe 标签。&lt;/p&gt;
        </iframe>
      </div>
    </div>
    {%else%}
    <p>无法链接到视频源，请确认摄像头是否打开</p>
    {%endif%}
    <div id="oper">
      <p>操作界面</p>
      <a class="operateItem" href="#">
        <img id="operFlagImg" src="{% static '/userManage/A.png'%}"></a>
    </div>
  </body>
</html>